AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BookStore with Lambda support.

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.tcs.evaluate.bookstore.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/bookstore-lambda-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /books
            Method: any

Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value: !Sub 'http://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/v2/books'
    Export:
      Name: LambdaSpringBootApi